<a href="https://colab.research.google.com/github/KRISHNPRIY2820/100-days-of-code-youtube/blob/main/Numpy_ai_camp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###*Introduction*:
Welcome to the NumPy tutorial! This session will help you understand how to work with NumPy, a powerful library for numerical computing in Python. We'll start with basic array operations and gradually move to more advanced topics like linear algebra and solving systems of equations.





In [ ]:
import numpy as np

In [ ]:
import random

###Question 0: list vs Array

In [ ]:
X=np.array([1,2,3,4])
print(X)
print(type(X))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
Y=[1,2,3,4]
print(Y)
print(type(Y))

[1, 2, 3, 4]
<class 'list'>


###Question 1: Creating Basic Arrays

In [ ]:
#Q1.1 How do create an array using NumPy?

In [ ]:
array1 = np.array([1, 2, 3, 4])

In [ ]:
print("Array 1:", array1)

Array 1: [1 2 3 4]


In [ ]:
#Q1.2: How do you create a 2x2 matrix with elements [[1, 2], [3, 4]] using NumPy?

In [ ]:
array2 = np.array([[1, 2], [3, 4]])

In [ ]:
print("Array 2:", array2)

Array 2: [[1 2]
 [3 4]]


In [ ]:
print(array2.ndim)

2


In [ ]:
print(array2.shape)

(2, 2)


In [ ]:
#Q1.3: How do you create a 3x3 array of zeros using NumPy?

In [ ]:
array3 = np.zeros((3, 3))

In [ ]:
print("Array 3:", array3)

Array 3: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Q1.4: How do you create a 2x4 array of ones using NumPy?

In [ ]:
array4 = np.ones((2, 4))

In [ ]:
print("Array 4:", array4)

In [ ]:
#Q1.5: How do you create a 3x3 identity matrix?

In [ ]:
# Create a 3x3 identity matrix
identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Q1.6 Generate 5 evenly spaced numbers between 0 and 10?

In [ ]:
arr = np.linspace(0, 10, 5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
#Q1.7Generate 5 random integers from 5 to 20?

In [ ]:
random_int=np.random.randint(5,20,5)
print(random_int)

[14  8  7  5 12]


In [ ]:
#Q1.8 What is the data  type of arrary [1 2 3 4]

In [ ]:
arr=np.array([1,2,3,4])

In [ ]:
print("data type",arr.dtype)

data type int64


In [ ]:
#Q1.9 convert the above data type into float

In [ ]:
new=np.float32(arr)
print("new_data_type",new.dtype)
print(new)

new_data_type float32
[1. 2. 3. 4.]


###Question 2: Element-wise Operations

In [ ]:
#Q2.1: Create two 1D arrays a = [1, 2, 3] and b = [4, 5, 6]. Perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
# Element-wise addition
print("a + b:", a + b)

In [ ]:
# Element-wise subtraction
print("a - b:", a - b)

In [ ]:
# Element-wise multiplication
print("a * b:", a * b)

In [ ]:
# Element-wise division
print("a / b:", a / b)

In [ ]:
#Q2.2: Create two 2D arrays a = [[1, 2, 3],[8,9,10]] and b =[[4, 5, 6],[1,0,3]]. Perform element-wise addition.

In [ ]:
a = np.array([[1, 2, 3],[8,9,10]])
b =np.array([[4, 5, 6],[1,0,3]])
# Element-wise addition
print("a + b:", a * b)

a + b: [[ 4 10 18]
 [ 8  0 30]]


##Question 3: Mathematical Functions

In [ ]:
#Q3.1: Calculate the sine, exponential, and square root of the array a = [1, 2, 3].

In [ ]:
a = np.array([1, 2, 3])

In [ ]:
# Sine of each element
print("sin(a):", np.sin(a))

In [ ]:
# Exponential of each element
print("exp(a):", np.exp(a))


In [ ]:
# Square root of each element
print("sqrt(a):", np.sqrt(a))

In [ ]:
#Q3.2: Calculate the min and max of the array a = [1, 2, 3].

In [ ]:
a=np.array([1,2,3])
max=np.max(a)
min=np.min(a)
print("max",max)
print("min",min)

max 3
min 1


###Question 4: Linear Algebra Operations

In [ ]:
#Q4.1: Create two 2x2 matrices a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]]. Compute their dot product, matrix multiplication, transpose of a, and the inverse of a.

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [ ]:
# Dot product
print("Dot product:\n", np.dot(a, b))

In [ ]:
# Matrix multiplication
print("Matrix multiplication (a @ b):\n", a @ b)

In [ ]:
# Transpose of a
print("Transpose of a:\n", a.T)

In [ ]:
# Inverse of a
a_inv = np.linalg.inv(a)
print("Inverse of a:\n", a_inv)

###Question 5: Eigenvalues and Eigenvectors

In [ ]:
#Q5.1: Find the eigenvalues and eigenvectors of the matrix a = [[1, 2], [3, 4]].

In [ ]:
a = np.array([[1, 2], [3, 4]])

In [ ]:
# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(a)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

###Question 6: Solving Linear Systems

In [ ]:
#Q6.1: Solve the system of linear equations:
#    {2x+3y=54x+y=11
#    {2x+3y=54x+y=11​

In [ ]:
# Coefficient matrix
A = np.array([[2, 3], [4, 1]])

In [ ]:
# Right-hand side vector
b = np.array([5, 11])

In [ ]:
# Solve for x and y
solution = np.linalg.solve(A, b)
print("Solution:", solution)

###**Advanced NumPy**: Questions and Answers

*Introduction*:
This session extends your knowledge of NumPy with advanced operations such as reshaping arrays, broadcasting, statistical operations, and working with structured arrays.

###Question 7: Reshaping and Flattening Arrays

In [ ]:
#Q7.1: Create a 1D array of the first 12 natural numbers and reshape it into a 3x4 matrix.

In [ ]:
# Create a 1D array of the first 12 natural numbers
array1d = np.arange(1, 13)
print("1D array:", array1d)

1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# Reshape the 1D array into a 3x4 matrix
array2d = array1d.reshape((3, 4))
print("3x4 matrix:\n", array2d)

3x4 matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#Q7.2: Flatten the 3x4 matrix back into a 1D array.

In [ ]:
# Flatten the 3x4 matrix back into a 1D array
flattened_array = array2d.flatten()
print("Flattened array:", flattened_array)

Flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


###Question 8: Broadcasting

**concept**:
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions and works its way forward. Two dimensions are compatible for broadcasting if:

1.They are equal.

2.One of them is 1.

If these conditions are met, NumPy will virtually replicate the smaller array along the dimension(s) where it is 1 to match the larger array, enabling element-wise operations.


In [ ]:
'''a = np.array([1, 2, 3,4])
b = np.array([1, 2, 3])
result = a + b
print(result)'''


'a = np.array([1, 2, 3,4])\nb = np.array([1, 2, 3])\nresult = a + b\nprint(result)'

In [ ]:
#Q8.1: Create a 3x3 matrix of ones and add a 1D array of [1, 2, 3] to it using broadcasting.

In [ ]:
# Create a 3x3 matrix of ones
matrix = np.ones((3, 3))
print("3x3 matrix of ones:\n", matrix)

3x3 matrix of ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Create a 1D array
array1d = np.array([1, 2, 3])
print("1D array:", array1d)

1D array: [1 2 3]


In [ ]:
# Add the 1D array to the 3x3 matrix using broadcasting
result = matrix + array1d
print("Result after broadcasting:\n", result)

Result after broadcasting:
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


###Question 9: Statistical Operations

In [ ]:
#Q9.1: Compute the mean, median, and standard deviation of an array [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].

In [ ]:
# Create an array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


In [ ]:
# Compute the mean
mean_value = np.mean(array)
print("Mean:", mean_value)

In [ ]:
# Compute the median
median_value = np.median(array)
print("Median:", median_value)

In [ ]:
# Compute the standard deviation
std_deviation = np.std(array)
print("Standard Deviation:", std_deviation)

###Question 10:Indexing and slicing

*Indexing in Multidimensional NumPy Arrays*

**Basic Indexing**:
Basic indexing works similarly to Python lists.

It’s 0-based, meaning the first element has an index of 0.

You can use negative indices to index from the end of the array.

**Basic slicing** extends Python’s concept of slicing to N dimensions.

Syntax: array[start:end:step]

In [ ]:
#10.1 find the number at index 2 in numpy array [1,2,8,4]

In [ ]:
arr=np.array([1,2,8,4])
print(arr[2])
#or
print(arr[-2])

8
8


In [ ]:
#10.2 finding the number at index[0,2] in 2d array [[9,8,7],[4,5,6]]

In [ ]:
var=np.array([[9,8,7],[4,5,6]])
print(var[0,2])

7


In [ ]:
#10.3 find the number at index[0,1,1] in array[[[1,2],[6,7]]]

In [ ]:
var=np.array([[[1,2],[6,7]]])
print(var[0,1,1])

7


In [ ]:
#10.4 If array is [0, 1, 2, 3, 4, 5] slice, it with index 1,3,5

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5])
arr[1:6:2] #6 is important
#arr[1:]


array([1, 2, 3, 4, 5])

In [ ]:
#10.5 using slicing,slice ([[2, 3],[5, 6]]) from [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
#For 2-D arrays, you can slice along both rows and columns.
#To extract a subarray, use array[start_row:end_row, start_col:end_col].


In [ ]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mat[0:2, 1:3]

array([[2, 3],
       [5, 6]])

###**Working with 3D NumPy Arrays**: Questions and Answers

*Introduction*:
This session will help you understand how to work with 3D NumPy arrays. We'll cover creating 3D arrays, slicing, reshaping, performing operations, and using various functions.

**Creating 3D Arrays**

In [ ]:
#Q23.1: Create a 3x3x3 3D array with random values.

In [ ]:
# Create a 3x3x3 3D array with random values
array_3d = np.random.rand(3, 3, 3)
print("3x3x3 3D array with random values:\n", array_3d)

**Slicing 3D Arrays**

In [ ]:
#Given a 3D array array_3d = np.arange(27).reshape((3, 3, 3)), extract the first 2x2x2 subarray.

In [ ]:
# Create a 3D array
array_3d = np.arange(27).reshape((3, 3, 3))
print("Original 3D array:\n", array_3d)

In [ ]:
# Extract the first 2x2x2 subarray
subarray = array_3d[:2, :2, :2]
print("First 2x2x2 subarray:\n", subarray)

**Reshaping 3D Arrays**

In [ ]:
#Reshape a 3D array array_3d = np.arange(27).reshape((3, 3, 3)) into a 1D array.

In [ ]:
# Create a 3D array
array_3d = np.arange(27).reshape((3, 3, 3))
print("Original 3D array:\n", array_3d)


Original 3D array:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
# Reshape the 3D array into a 1D array
array_1d = array_3d.reshape(-1)
print("Reshaped 1D array:", array_1d)

Reshaped 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


**Indexing 3D Arrays**

In [ ]:
# Access the element at position (2, 1, 0) in a 3x3x3 array.

In [ ]:
# Create a 3x3x3 array
array_3d = np.arange(27).reshape((3, 3, 3))
print("Original 3D array:\n", array_3d)

# Access the element at position (2, 1, 0)
element = array_3d[2, 1, 0]
print("Element at position (2, 1, 0):", element)


**Summing Over Axes**

In [ ]:
#Sum the elements of a 3x3x3 array along the third axis.

In [ ]:
# Create a 3x3x3 array with random values
array_3d = np.random.rand(3, 3, 3)
print("Original 3D array:\n", array_3d)

Original 3D array:
 [[[0.39016647 0.54855094 0.04921409]
  [0.57067693 0.77896678 0.40089567]
  [0.32441222 0.38315842 0.36977992]]

 [[0.49938692 0.25892774 0.76841737]
  [0.82150514 0.02705974 0.99321945]
  [0.89272779 0.08257666 0.09823982]]

 [[0.11636807 0.07015043 0.28683748]
  [0.44564451 0.13673728 0.67578617]
  [0.61849474 0.13557587 0.2234694 ]]]


In [ ]:
# Sum the elements along the third axis
sum_along_axis = np.sum(array_3d, axis=0)
print("Sum along the third axis:\n", sum_along_axis)

Sum along the third axis:
 [[1.00592146 0.87762911 1.10446894]
 [1.83782657 0.9427638  2.06990129]
 [1.83563475 0.60131095 0.69148914]]


###High-level Concepts in Numpy

In [ ]:
a = np.arange(2*3*4).reshape(2,3,4)
print(a)
#a is a 3D array with shape (2, 3, 4).
#The first dimension has size 2
#The second dimension has size 3.
#The third dimension has size 4.

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


**Sigmoid**
Let's say a vector $x \in \mathbb{R}^n$. The sigmoid function is defined as:

$\operatorname{sigmoid}(x_i) = \frac{1}{1 + e^{-x_{i}}} \forall i$

In [ ]:
def sigmoid(a):
  e = np.exp(-a)
  return 1/(1+e)

In [ ]:
sigmoid(a.ravel())

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661,
       0.9999546 , 0.9999833 , 0.99999386, 0.99999774, 0.99999917,
       0.99999969, 0.99999989, 0.99999996, 0.99999998, 0.99999999,
       1.        , 1.        , 1.        , 1.        ])

**Tanh**
Let's say a vector $x \in \mathbb{R}^n$. The tanh function is defined as:

$\operatorname{tanh}(x_i) = \frac{e^{2x_i} - 1}{e^{2x_i} + 1} \forall i$

In [ ]:
def tanh(a):
  e = np.exp(2*a)
  return (e - 1) / (e + 1)

**Softmax**
Let's say a vector $x \in \mathbb{R}^n$. The softmax function is defined as:

$\operatorname{softmax}(x_i) = \frac{e^{x_{i}}}{\sum_{j}e^{x_{j}}} \forall i$

In [ ]:
def softmax(a):
  e = np.exp(a)
  return e / np.sum(e)

In [ ]:
softmax(a.ravel())

array([6.48674509e-11, 1.76328013e-10, 4.79309234e-10, 1.30289758e-09,
       3.54164282e-09, 9.62718331e-09, 2.61693974e-08, 7.11357975e-08,
       1.93367146e-07, 5.25626399e-07, 1.42880069e-06, 3.88388295e-06,
       1.05574884e-05, 2.86982290e-05, 7.80098743e-05, 2.12052824e-04,
       5.76419338e-04, 1.56687021e-03, 4.25919482e-03, 1.15776919e-02,
       3.14714295e-02, 8.55482149e-02, 2.32544158e-01, 6.32120559e-01])

**Root Mean Squared Error**

Let's say a vectors $x,y \in \mathbb{R}^n$. The RMSE function is defined as:

$\operatorname{RMSE}(x,y) = \sqrt{\sum_i (x_i - y_i)^2}$

In [ ]:
def rmse(x,y):
  return np.sqrt(np.sum((x-y)**2))

**Cross Entropy**

Let's say a vectors $x,y \in [0,1]^n$. The CrossEntropy function is defined as:

$\operatorname{CrossEntropy}(x,y) = - \sum_i x_i \log y_i$

In [ ]:
def cross_entropy(x,y):
  return -np.sum(x * np.log(y))

###**Machine Learning with NumPy: Questions and Answers**

Shuffling Datasets

In [ ]:
#Shuffle the rows of a 2D array data = [[1, 2], [3, 4], [5, 6], [7, 8]].

In [ ]:
# Define the 2D array
data = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

Generating Synthetic Data

In [ ]:
#Generate a synthetic dataset with 100 samples, each having 3 features.

In [ ]:
# Generate a synthetic dataset with 100 samples, each having 3 features
synthetic_data = np.random.randn(100, 3)
print("Synthetic data:\n", synthetic_data)

**Confusion Matrix**



      
             Predicted 0    Predicted 1
    Actual 0      TN              FP
    Actual 1      FN              TP


In [ ]:
import numpy as np

# Define true labels and predicted labels
y_true = np.array([0, 1, 1, 0, 1, 1, 0, 0, 1, 0])
y_pred = np.array([0, 1, 0, 0, 1, 1, 0, 1, 1, 1])

# Compute the confusion matrix
confusion_matrix = np.zeros((2, 2), dtype=int)
for t, p in zip(y_true, y_pred):
    confusion_matrix[t, p] += 1

print("Confusion Matrix:\n", confusion_matrix)


Confusion Matrix:
 [[3 2]
 [1 4]]
